apiVersion: v1
kind: ReplicationController
metadata:
  name: simmemleak
spec:
  replicas: 1
  selector:
    name: simmemleak
  template:
    metadata:
      labels:
        name: simmemleak
    spec:
      containers:
      - name: simmemleak
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        image: saadali/simmemleak

