apiVersion: v1
kind: ReplicationController
metadata:
  name: sleepypod
spec:
  replicas: 16
  selector:
    name: sleepy
  template:
    metadata:
      labels:
        name: sleepy
    spec:
      containers:
      - name: sleepypod
        image: saadali/sleepy

