apiVersion: v1
kind: ReplicationController
metadata:
  name: sleepypod
spec:
  replicas: 200 #replicas: 5000
  selector:
    name: sleepy
  template:
    metadata:
      labels:
        name: sleepy
    spec:
      containers:
      - name: sleepycontainer1
        image: saadali/sleepy:v0.2
        resources:
          limits:
            cpu: "0.002"
            memory: "4Mi"
      - name: sleepycontainer2
        image: saadali/sleepy:v0.2
        resources:
          limits:
            cpu: "0.002"
            memory: "4Mi"

